[package]
name = "minml_rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "minml_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
regex = "1"
once_cell = "1"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
